const STORE = {
  name: '鴨餃子とワインバル オペレッタ52｜東梅田 居酒屋バル',
  shortName: 'オペレッタ52',
  romanized: 'Kamo Gyoza to Wine Bar Operetta 52',
  address: '〒530-0057 大阪府大阪市北区曾根崎２丁目１−１２ 国道ビル ラ オカシオン 1F',
  phone: '06-6948-6527',
  hours: '17:00〜翌2:00',
  closed: '定休日なし',
  maps: 'https://www.google.com/maps/search/?api=1&query=%E9%B4%A8%E9%A4%83%E5%AD%90%E3%81%A8%E3%83%AF%E3%82%A4%E3%83%B3%E3%83%90%E3%83%AB%20%E3%82%AA%E3%83%9A%E3%83%AC%E3%83%83%E3%82%BF52%EF%BD%9C%E6%9D%B1%E6%A2%85%E7%94%B0%20%E5%B1%85%E9%85%92%E5%B1%8B%E3%83%90%E3%83%AB',
  official: 'https://www.operetta52.com/',
  reserve: 'https://tabelog.com/osaka/A2701/A270101/27082545/',
  instagram: 'https://www.instagram.com/operetta52/',
};

const jpKeywords = ['梅田 居酒屋','東梅田 居酒屋','梅田 バル','東梅田 バル','梅田 ワインバル','東梅田 ワインバル','梅田 餃子','東梅田 餃子','梅田 鴨料理','東梅田 鴨料理','梅田 鴨餃子','お初天神 居酒屋','お初天神 バル','お初天神 ワイン','曽根崎 居酒屋','曾根崎 居酒屋','大阪駅 居酒屋','北新地駅 居酒屋','梅田 ディナー','東梅田 ディナー','梅田 夜ごはん','梅田 飲み会','梅田 ワイン','東梅田 ワイン','鴨餃子 ワイン','鴨料理 ワイン','創作鴨料理','モダン居酒屋','鴨肉料理 大阪','餃子バル 大阪','ワインと餃子','ワインと鴨料理','オペレッタ52','オペレッタゴートゥー','オペレッタ52 梅田','オペレッタ52 東梅田','オペレッタ52 予約','オペレッタ52 メニュー','オペレッタ52 営業時間','オペレッタ52 アクセス','オペレッタ52 電話','オペレッタ52 住所','オペレッタ52 Instagram','オペレッタ52 食べログ','梅田 居酒屋 予約','東梅田 居酒屋 予約','梅田 バル 予約','東梅田 バル 予約','梅田駅 徒歩 居酒屋','東梅田駅 徒歩 居酒屋','北新地駅 徒歩 バル','大阪駅 徒歩 バル','梅田 鴨肉','東梅田 鴨肉','梅田 シャンパン餃子','東梅田 シャンパン餃子','梅田 フォアグラ餃子','東梅田 フォアグラ餃子','梅田 鴨パストラミ','梅田 鴨コンフィ','東梅田 鴨コンフィ','梅田 創作料理','東梅田 創作料理','梅田 ワイン ディナー','東梅田 ワイン ディナー','お初天神 鴨料理','お初天神 餃子','お初天神 ディナー','曾根崎 バル','曽根崎 バル','曾根崎 ワイン','梅田 グラスワイン','東梅田 グラスワイン','梅田 カウンター バル','東梅田 カウンター バル','梅田 17時 営業','東梅田 17時 営業','梅田 深夜 居酒屋','東梅田 深夜 居酒屋','梅田 日曜営業 居酒屋','東梅田 日曜営業','大阪 梅田 鴨餃子','大阪 梅田 ワインバル','大阪 鴨料理 居酒屋','大阪 餃子 ワイン','梅田 テイクアウト 鴨餃子','東梅田 テイクアウト','梅田 モダン居酒屋','東梅田 モダン居酒屋','梅田 食事 予約','東梅田 食事 予約','梅田 レストラン 予約','東梅田 レストラン','梅田 居酒屋 鴨','東梅田 居酒屋 鴨','梅田 餃子 ディナー','東梅田 餃子 ディナー','鴨餃子 オペレッタ52','梅田 オペレッタ','東梅田 オペレッタ','国道ビル 居酒屋','ラ オカシオン 居酒屋'];
const enKeywords = ['Operetta 52','Operetta 52 Osaka','Operetta 52 Umeda','Operetta 52 Higashi Umeda','Kamo Gyoza to Wine Bar Operetta 52','duck gyoza Osaka','duck gyoza Umeda','duck dumplings Osaka','duck dumplings Umeda','wine bar Umeda','wine bar Higashi Umeda','izakaya Umeda','izakaya Higashi Umeda','modern izakaya Osaka','modern izakaya Umeda','duck restaurant Osaka','duck restaurant Umeda','Japanese restaurant Umeda','restaurant near Higashi Umeda Station','restaurant near Umeda Station','restaurant near Osaka Station','restaurant near Kitashinchi Station','Umeda dinner','Higashi Umeda dinner','Osaka local dining','Umeda local dining','Japanese wine bar Osaka','gyoza and wine Osaka','gyoza and wine Umeda','duck cuisine Osaka','duck cuisine Umeda','creative duck dishes','foie gras gyoza','champagne gyoza','duck pastrami Osaka','duck confit Umeda','wine and duck dishes','Umeda restaurant reservation','Higashi Umeda restaurant reservation','Osaka restaurant reservation','dinner reservation Umeda','bar near Umeda Station','izakaya near Higashi Umeda Station','dining near Ohatsu Tenjin','Ohatsu Tenjin izakaya','Ohatsu Tenjin wine bar','Sonezaki restaurant','Sonezaki izakaya','Osaka wine dining','Umeda evening dining','Higashi Umeda evening dining','duck meat restaurant Japan','Japanese dumpling bar','Osaka gyoza bar','Umeda gyoza bar','wine restaurant Umeda','casual dining Umeda','late night izakaya Umeda','Sunday dining Umeda','takeout duck gyoza','restaurant in Kita Ward Osaka','Osaka Kita Ward izakaya','Umeda food and wine','Higashi Umeda food and wine','Japanese bar dining Osaka'];

const jsonLd = {
  '@context': 'https://schema.org', '@type': 'Restaurant', name: STORE.name,
  alternateName: [STORE.shortName, STORE.romanized], url: 'https://operetta52.vercel.app/', telephone: STORE.phone,
  address: { '@type':'PostalAddress', postalCode:'530-0057', addressRegion:'大阪府', addressLocality:'大阪市北区', streetAddress:'曾根崎２丁目１−１２ 国道ビル ラ オカシオン 1F', addressCountry:'JP' },
  servesCuisine: ['鴨餃子','鴨料理','創作料理','ワインバル'], priceRange:'￥2,000〜￥6,000',
  openingHoursSpecification: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(day=>({'@type':'OpeningHoursSpecification',dayOfWeek:`https://schema.org/${day}`,opens:'17:00',closes:'02:00'})),
  hasMap: STORE.maps, acceptsReservations: true, sameAs:[STORE.official,STORE.instagram,STORE.reserve]
};

function Links(){return <div className="actions"><a className="primary" href={STORE.reserve}>席を予約</a><a href={STORE.maps}>Google マップ</a><a href={`tel:${STORE.phone.replaceAll('-','')}`}>電話する</a></div>}

export default function Home(){return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
  <header><a className="brand" href="#top">OPERETTA <b>52</b></a><nav><a href="#features">特徴</a><a href="#info">店舗情報</a><a href="#access">アクセス</a><a href="#faq">FAQ</a><a href="#english">English</a></nav></header>
  <main id="top">
    <section className="hero"><div><p className="eyebrow">HIGASHI UMEDA · DUCK GYOZA · WINE</p><h1>鴨餃子とワインバル<br/><span>オペレッタ52</span><small style={{display:'block',fontSize:'clamp(15px, 2vw, 22px)',marginTop:12,letterSpacing:'.04em'}}>｜東梅田 居酒屋バル</small></h1><p className="lead">梅田・東梅田で鴨料理とワインを楽しめる居酒屋バル。お初天神近くで、名物の鴨餃子をはじめ、創作鴨料理と料理に合わせたワインを味わえます。</p><Links/></div><div className="heroArt" aria-label="鴨餃子とワインを表現した装飾"><span>鴨</span><small>GYOZA × WINE</small></div></section>
    <section className="quick"><div><small>営業時間</small><strong>{STORE.hours}</strong></div><div><small>エリア</small><strong>東梅田・お初天神</strong></div><div><small>電話</small><strong>{STORE.phone}</strong></div></section>
    <section id="features"><p className="eyebrow">FEATURES</p><h2>梅田の居酒屋で楽しむ、鴨餃子とワイン</h2><p className="sectionLead">オペレッタ52は、大阪・梅田の中でも東梅田駅やお初天神、北新地駅から立ち寄りやすい居酒屋バルです。一般的な餃子居酒屋とはひと味違う鴨餃子と、多彩な鴨料理、ワインの組み合わせを楽しめます。梅田で居酒屋を探している方、東梅田で食事やワインを楽しみたい方に、店の特徴とアクセス情報を分かりやすくご案内します。</p><div className="cards"><article><b>01</b><h3>梅田で味わう名物・鴨餃子</h3><p>鴨肉の旨みを生かした鴨餃子が看板料理。フォアグラ餃子やシャンパン餃子など、ワインバルらしい個性豊かな餃子も楽しめます。</p></article><article><b>02</b><h3>東梅田で楽しむ創作鴨料理</h3><p>鴨のパストラミ、鴨のコンフィ、鴨の盛り合わせなど、餃子だけでなくさまざまな鴨料理を楽しめます。</p></article><article><b>03</b><h3>居酒屋使いできるワインバル</h3><p>鴨料理とワインの組み合わせを気軽に楽しめるのがオペレッタ52の特徴。梅田での夕食、友人との食事、仕事帰りの一杯にも利用しやすい居酒屋バルです。</p></article></div></section>
    <section id="menu" className="dark"><p className="eyebrow">MENU HIGHLIGHTS</p><h2>オペレッタ52の鴨料理メニュー</h2><p>梅田の居酒屋で餃子とワインを楽しみたいときに。名物の鴨餃子を中心に、鴨肉の味わいを生かした料理を用意しています。</p><div className="menuGrid"><span>鴨餃子</span><span>フォアグラ餃子</span><span>シャンパン餃子</span><span>鴨のパストラミ</span><span>鴨のコンフィ</span><span>鴨の4種盛り合わせ</span></div><p className="note">内容・価格・提供状況は変更される場合があります。最新情報は予約ページまたは店舗へお問い合わせください。</p><a className="textLink" href="https://tabelog.com/osaka/A2701/A270101/27082545/dtlmenu/">食べログでメニューを見る →</a></section>
    <section id="info"><p className="eyebrow">INFORMATION</p><h2>店舗基本情報</h2><dl><div><dt>正式店名</dt><dd>{STORE.name}</dd></div><div><dt>英語・ローマ字</dt><dd>{STORE.romanized}</dd></div><div><dt>業態</dt><dd>モダン居酒屋レストラン／鴨餃子・鴨料理・ワインバル</dd></div><div><dt>住所</dt><dd>{STORE.address}</dd></div><div><dt>電話番号</dt><dd><a href="tel:0669486527">{STORE.phone}</a></dd></div><div><dt>営業時間</dt><dd>{STORE.hours}</dd></div><div><dt>定休日</dt><dd>{STORE.closed}</dd></div><div><dt>公式サイト</dt><dd><a href={STORE.official}>operetta52.com</a></dd></div><div><dt>予約</dt><dd><a href={STORE.reserve}>食べログから予約</a></dd></div><div><dt>Instagram</dt><dd><a href={STORE.instagram}>@operetta52</a></dd></div></dl></section>
    <section id="access" className="access"><div><p className="eyebrow">ACCESS</p><h2>梅田・東梅田の居酒屋バル</h2><p>{STORE.address}</p><p>大阪メトロ谷町線の東梅田駅、JR東西線の北新地駅から徒歩圏内です。大阪駅・梅田駅からもアクセスしやすく、お初天神周辺で居酒屋やワインバル、鴨料理の店を探す際に便利な立地です。</p><Links/></div><a className="mapCard" href={STORE.maps}><span>Google Maps</span><b>地図とルートを開く ↗</b><small>Google Maps APIは使用していません</small></a></section>
    <section id="faq"><p className="eyebrow">FAQ</p><h2>梅田の居酒屋・オペレッタ52について</h2><details><summary>オペレッタ52は梅田のどこにありますか？</summary><p>{STORE.address}です。東梅田駅と北新地駅から徒歩圏内で、お初天神にも近い場所にあります。</p></details><details><summary>梅田駅や大阪駅からアクセスできますか？</summary><p>はい。大阪駅・梅田駅エリアから徒歩でアクセスできます。最寄り駅は東梅田駅と北新地駅です。</p></details><details><summary>営業時間と定休日は？</summary><p>営業時間は17:00〜翌2:00、定休日はありません。臨時変更については店舗へお問い合わせください。</p></details><details><summary>どのような料理を楽しめますか？</summary><p>名物の鴨餃子を中心に、フォアグラ餃子、シャンパン餃子、鴨のパストラミ、鴨のコンフィなどを楽しめます。</p></details><details><summary>梅田で居酒屋として予約できますか？</summary><p>はい。食べログの予約ページ、Googleマップの予約リンク、または電話をご利用ください。</p></details><details><summary>公式リンクはどこですか？</summary><p>このページ下部に、Googleマップ、公式サイト、食べログ、Instagramなどの店舗関連リンクをまとめています。</p></details></section>
    <section id="english" className="english"><p className="eyebrow">ENGLISH GUIDE</p><h2>Operetta 52 — Umeda Izakaya & Duck Gyoza Wine Bar</h2><p><b>Kamo Gyoza to Wine Bar Operetta 52</b> is a modern izakaya-style restaurant in Umeda, Osaka, near Higashi Umeda Station, Kitashinchi Station and Ohatsu Tenjin. The restaurant serves duck gyoza, creative duck dishes and wine, making it a distinctive choice for dinner and local dining in the Umeda area.</p><div className="englishGrid"><p><small>AREA</small>Higashi Umeda, Umeda, Osaka</p><p><small>TYPE</small>Modern izakaya / Duck gyoza / Wine bar</p><p><small>ADDRESS</small>1F, Kokudo Bldg. La Occasion, 2-1-12 Sonezaki, Kita-ku, Osaka 530-0057, Japan</p><p><small>HOURS</small>5:00 p.m.–2:00 a.m. / No regular closing day</p><p><small>RESERVATION</small>Online via Tabelog or by phone</p><p><small>ACCESS</small>Walking distance from Higashi Umeda, Kitashinchi, Umeda and Osaka stations</p></div><Links/></section>
    <section className="keywords"><h2>関連する検索キーワード</h2><p>{jpKeywords.map((k,i)=><span key={i}>{k}</span>)}</p><h3>English search terms</h3><p>{enKeywords.map((k,i)=><span key={i}>{k}</span>)}</p></section>
    <section className="links"><h2>公式サイト・予約サイト</h2><p>オペレッタ52の公式SNS、予約、メニュー、店舗情報はこちらからご覧いただけます。</p><div className="linkGrid"><a href={STORE.maps}>Google マップ・店舗プロフィール <b>↗</b></a><a href={STORE.official}>公式サイト <b>↗</b></a><a href="https://www.operetta52.com/shop.html">公式サイト・店舗案内 <b>↗</b></a><a href="https://operetta52.net/">公式店舗サイト <b>↗</b></a><a href={STORE.instagram}>Instagram @operetta52 <b>↗</b></a><a href={STORE.reserve}>食べログ・予約 <b>↗</b></a><a href="https://tabelog.com/osaka/A2701/A270101/27082545/dtlmenu/">食べログ・メニュー <b>↗</b></a><a href="https://www.hotpepper.jp/strJ001109692/">ホットペッパーグルメ・予約 <b>↗</b></a><a href="https://r.gnavi.co.jp/fme1hbwp0000/">楽天ぐるなび・予約 <b>↗</b></a><a href="https://operetta52.foodre.jp/">Retty店舗ページ <b>↗</b></a><a href="https://epark.jp/shopinfo/hit620465/">EPARK店舗情報 <b>↗</b></a><a href="https://autoreserve.com/ja/restaurants/137mzRCDqZCR85jthD8V">AutoReserve <b>↗</b></a><a href="https://www.ubereats.com/jp/osaka/food-delivery/%E3%82%AA%E3%83%98%E3%83%AC%E3%83%83%E3%82%BF52-%E3%81%8A%E5%88%9D%E5%A4%A9%E7%A5%9E%E5%BA%97-operetta52-ohatsu-tenjin/aq57EzNmSYayGRCe9P3nvg">Uber Eats <b>↗</b></a><a href="https://kaiten-portal.jp/spots/830179">開店ポータル店舗情報 <b>↗</b></a></div></section>
  </main>
  <footer><p><b>{STORE.name}</b></p><p>{STORE.address}<br/>{STORE.phone}</p><small>掲載情報はGoogleビジネスプロフィールおよび店舗公式・予約媒体をもとに整理しています。営業状況は来店前に店舗へご確認ください。</small></footer>
  </>}
